import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Import Inter font
import "./globals.css";

const inter = Inter({
  variable: "--font-inter", // Define a CSS variable for the font
  subsets: ["latin"], // Specify subsets (e.g., "latin", "cyrillic")
});

export const metadata: Metadata = {
  title: "NovaAI - Futuristic AI Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}